# SORX <xsorx.github.io>
VERSION="1.1.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="SORX"
ORG_URL="https://sorx.co/"
ORG_LOGO = ""

[[CURRENCIES]]
code = "SORX"
name = "SORX"
issuer = "GDPTX2Z3HTJKCHTT5JHCL7M5MD7P2HVV7QUDCTBIHW2BYLO3XR4VSRSA"
is_asset_anchored = false
display_decimals = 7
desc="SORX stands as a beacon of innovation within the Stellar network, bringing efficiency, liquidity, and multifaceted utility to the cryptocurrency trading landscape."
image="https://magiccrypto.github.io/icons/MVOTEicon.png"
